### ISSUE TITLE
Générer des boites à moustache d'expérience par thématique de recherche

### ISSUE THREAD

**Issue by danielleberre** [societe-informatique-de-france/referentiel-pratiques-publication-2019#2]
Il serait intéressant d'analyser l'expériences déclarée par thématique de recherche, pour vérifier si il y a des différences.

Je ne sais pas comment le faire proprement en R.

**Comment by romainwallon** [comment]
Normalement, en ajoutant ces lignes dans le *chunk* qui crée la boîte à moustaches, cela devrait faire l'affaire :

```r
experience$theme = answers$theme
boxplot(experience[,1]~experience[,2], las=3)
```

**Comment by danielleberre** [comment]
Effectivement, ça fonctionne :

![experience-1](https://user-images.githubusercontent.com/27728854/73590850-9b307600-44e7-11ea-9251-3c38704957d0.png)

comment changer la légende par des acronymes ? (SI, Algo/RO, IA, etc)

**Comment by romainwallon** [comment]
Voici une solution possible (il faut remplacer les lignes précédentes par celles-ci): 

```r
experience$theme = as.factor(answers$theme)
levels(experience$theme) = c("RO", "Archi", "Bioinfo", "GL", "Images", "Fondamentale", "Industrielle", "IA", "IHM", "Modélisation", "Réseaux", "Sys Information", "Sys Informatiques")
boxplot(experience[,1]~experience[,2], las=3)
```

**Comment by danielleberre** [comment]
Effectivement, cela fonctionne. 
Je ne comprends pas pourquoi l'ordre des thématiques n'est pas préservé.
J'ai ai profité pour ajouter des boites à moustaches par association d'origine.
